apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone1
  template:
    metadata:
      labels:
        app: capstone1
    spec:
      containers:
        - name: web
          image: divisha22/capstone
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: capstone1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

