

---
- name: Apply LoadBalancer Service
  hosts: localhost
  tasks:
    - name: Apply Kubernetes LoadBalancer Service
      command: kubectl apply -f ~/project/deploy_service.yml
      environment:
        KUBECONFIG: ~/project/deploy_service.yml